In [1]:
from scipy.io import loadmat
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
%matplotlib inline

In [3]:
import matplotlib.pyplot as plt
from sgsom import GSOM

ImportError: No module named sgsom

In [4]:
dat = loadmat('counts.mat')

IOError: [Errno 2] No such file or directory: 'counts.mat'

In [5]:
cd ..

/home


In [6]:
from RBM import RBM

ImportError: No module named RBM

In [7]:
dat['counts'].shape
x = dat['counts']

NameError: name 'dat' is not defined

In [10]:
x=x.reshape((x.shape[0], x.shape[1]*x.shape[2]), order='F')

NameError: name 'x' is not defined

In [11]:
x[0]

NameError: name 'x' is not defined

In [12]:
rbm = RBM(visible=24, hidden=10)
scaler = StandardScaler()
scaler.fit_transform(x)
x_bin = x
x_bin[x>0] = 1

NameError: name 'RBM' is not defined

In [13]:
x_bin

NameError: name 'x_bin' is not defined

In [14]:
for i in range(1000):
    if i < 500:
        momentum = 0.9
        eps = 0.01
    else : 
        eps = 0.005
        momentum = 0.5
    rbm.train(x_bin, momentum=momentum, eps = eps)

NameError: name 'rbm' is not defined

In [15]:
rbm.reconstruct()[0]

NameError: name 'rbm' is not defined

In [16]:
x_prime = scaler.inverse_transform(rbm.reconstruct())
x_prime[0]

NameError: name 'scaler' is not defined

In [17]:
gsom = GSOM(dims=24, sf = 0.999999999, fd = 0.99, max_nodes = 1500, min_nodes = 100, radius=20)

NameError: name 'GSOM' is not defined

In [18]:
gsom.train_batch(x_prime, 10, 0.01)

NameError: name 'gsom' is not defined

In [19]:
h, v = gsom.predict(x).T

NameError: name 'gsom' is not defined

In [20]:
plt.scatter(h, v, s = 1)

NameError: name 'h' is not defined

In [21]:
for i, j, t in zip(h, v, range(x.shape[0])):
    plt.text(i, j, t, color = 'purple', fontsize = 8)

NameError: name 'h' is not defined

In [22]:
plt.show()

In [23]:
coords = gsom.predict(x)
coords

NameError: name 'gsom' is not defined

In [24]:
ar = []
for ind in coords:
    ar.append(str(ind))

clusters = {}
    
for ind in np.unique(np.array(ar)):
    clusters[ind] = np.where(np.array(ar)==ind)
clusters

NameError: name 'coords' is not defined

In [21]:
from sklearn.manifold import TSNE, Isomap

In [22]:
clus = TSNE()

In [23]:
h, v= clus.fit_transform(x).T

In [30]:
plt.scatter(h, v, marker = '1')
i = 0
for hi, vi in zip(h, v):
    plt.text(hi, vi, str(i), color = 'purple', fontsize=8)
    i +=1
# for label, xi, yi in zip(range(x.shape[0]), x, y):    
#     plt.annotate(
#             str(label), 
#             xy = (xi, yi), xytext = (20, -20),
#             textcoords = 'offset points', ha = 'right', va = 'bottom',
#             bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
#             arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
plt.show()

In [72]:
dat['counts'][2]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [33]:
for seq in dat['counts'][696].T:
    plt.plot(range(seq.shape[0]), seq)
    
plt.show()

In [11]:
import numpy as np

In [12]:
a = np.random.random(size=(3, 3, 3))
a

array([[[ 0.8463927 ,  0.94319539,  0.86745467],
        [ 0.92863841,  0.22943464,  0.66658845],
        [ 0.87713992,  0.41112445,  0.34455244]],

       [[ 0.82506366,  0.51476107,  0.5975684 ],
        [ 0.62536136,  0.10120957,  0.97505688],
        [ 0.39746355,  0.37316931,  0.96337444]],

       [[ 0.81382972,  0.32531585,  0.10152901],
        [ 0.4254729 ,  0.66304115,  0.01784257],
        [ 0.37291229,  0.2271182 ,  0.27964254]]])

In [13]:
a.reshape(3,9, order=2)

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  if __name__ == '__main__':


array([[ 0.8463927 ,  0.92863841,  0.87713992,  0.94319539,  0.22943464,
         0.41112445,  0.86745467,  0.66658845,  0.34455244],
       [ 0.82506366,  0.62536136,  0.39746355,  0.51476107,  0.10120957,
         0.37316931,  0.5975684 ,  0.97505688,  0.96337444],
       [ 0.81382972,  0.4254729 ,  0.37291229,  0.32531585,  0.66304115,
         0.2271182 ,  0.10152901,  0.01784257,  0.27964254]])

In [42]:
import numpy as np
np.linalg.norm(np.array([[1, 0], [1, 0]])-np.array([2, 3]), axis = 1)

array([ 3.16227766,  3.16227766])

In [43]:
a = {'a':1, 'b':2}

In [44]:
a[['a', 'b']]

TypeError: unhashable type: 'list'