In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial import Delaunay, ConvexHull

In [18]:
def  triangulate(grid):
    adj = np.zeros((grid.shape[0], grid.shape[0]))
    tri = Delaunay(grid)
    chull = ConvexHull(grid).simplices
#     print chull
    for simplegrid in tri.simplices:
        for vert in simplegrid:
            for vert2 in simplegrid:
                adj[vert][vert2] = 1
#     for line in chull:
#         adj[line[0]][line[1]]=0
#         adj[line[1]][line[0]]=0
    
    return adj

def get_neighbors(point, grid):
    
    G = triangulate(grid)   
    return np.where(G[point])[0]
#     print np.where(np.linalg.norm(grid - grid[point], axis =1) < r) [0]

In [2]:
X = np.array(pd.read_csv('/home/senanayaked/data/2D3C_RAW.csv', header = None))

In [54]:
C = np.random.randn(100, X.shape[1])
Y = np.random.random((100, 2))
E = np.zeros(100)
GT = -np.log(0.7)*X.shape[1]
FD = 0.5
for i in range(3):
#### Training Phase ##### 
        for x in X:
            bmu = np.argmin(np.linalg.norm(C-x, axis=1))
            neis = get_neighbors(bmu, Y)
            dists = np.linalg.norm(Y[neis]-Y[bmu], axis = 1)
            E[bmu] += np.linalg.norm(C[bmu] - x)
#             dists /= dists.max()
            h = np.exp(-dists**2/2)
            C[neis] += np.array([h]).T * (x - C[neis]) * 0.1
        
        chull = np.unique(ConvexHull(Y).simplices)[0]
        
        #### Growing Phase #####
        for i in range(C.shape[0]):
            if np.any(i == chull):
                if E[i] > GT:
                    neis = get_neighbors(i, Y)
                    y_ns = Y[i] + (Y[i]-Y[neis])/np.array([np.linalg.norm(Y[i] - Y[neis])]*np.array([np.linalg.norm(C[i]-C[neis])]).T
                    Y = np.append(Y, y_ns, axis=0)
                    E = np.append(E, np.zeros(y_ns.shape[0]))
                    C= np.append(C, 2*C[i] - C[neis], axis = 0)

    

In [52]:
(Y[0] - Y[neis]) * np.array([np.linalg.norm(C[0]-C[neis])]).T

array([[ 0.        ,  0.        ],
       [ 0.08666215, -0.6924986 ],
       [-0.74132305,  1.38574701],
       [ 1.29574238, -0.7058422 ],
       [ 0.11812206, -0.94388797],
       [ 0.38723558, -1.44693891],
       [-1.31204768,  4.42722825]])

In [ ]:
plt.scatter(Y.T[0][:100], Y.T[1][:100], c = 'blue', alpha=0.5)
plt.scatter(Y.T[0][100:], Y.T[1][100:], c = 'red', alpha = 0.5)
plt.show()

In [44]:
np.unique(chull)

array([ 9, 14, 16, 18, 22, 23, 24, 25], dtype=int32)

In [46]:
9 in chull

TypeError: argument of type 'numpy.int32' is not iterable

In [47]:
chull

0

In [50]:
Y

array([[ 0.02505033,  0.71021238],
       [ 0.98969126,  0.50767966],
       [ 0.74913656,  0.9504886 ],
       [ 0.92949068,  0.45912271],
       [ 0.02505033,  0.71021238],
       [-0.97482686,  0.37841944],
       [-1.22387451,  1.05693744],
       [ 0.98969126,  0.50767966],
       [ 1.05178601,  0.39337672],
       [ 1.00523092,  0.52021375]])