In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sys

In [7]:
X = np.array(pd.read_csv('/home/senanayaked/data/spiral.csv', header=None))#np.array([[1,0,0], [0,1,0], [1.41, 1.41,0],[0.8,0.8,-0.8],[0.8, 0.8, 0.8]])
c = plt.cm.Set1(np.array(range(X.shape[0])).astype(float)/X.shape[0])#np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1],[0, 1, 1], [0, 0, 0]])
Y = np.random.random((X.shape[0], 2))*X.size
# plt.scatter(Y.T[0], Y.T[1], c = c, alpha = 0.5)
# plt.show()

In [8]:
cm = np.array(['red', 'green', 'blue'])
X = np.array(pd.read_csv('/home/senanayaked/data/2D3C_RAW.csv', header=None))#np.array([[1,0,0], [0,1,0], [1.41, 1.41,0],[0.8,0.8,-0.8],[0.8, 0.8, 0.8]])
c = cm[np.array(range(X.shape[0]))/500]#np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1],[0, 1, 1], [0, 0, 0]])
Y = np.random.random((X.shape[0], 2))*X.size


In [9]:
inp = np.array(pd.read_csv('~/data/mnist_train.csv', header=None))[:2500]
X = inp[:, 1:]
L = inp[:, 0].astype(float)
Y = np.random.random((X.shape[0], 2))*np.sqrt(X.size)
C = plt.cm.Set1(L/10)

In [12]:

errors = []
br = False
for j in range(10):
    sys.stdout.write('\riteration %i'%(j))
    for i in range(X.shape[0]):
        d = np.linalg.norm(Y - Y[i], axis = 1)#[neis]
        d/=d.sum()
        neis = d.argsort()[:4]      
        D = np.linalg.norm(X -X[i], axis = 1)
        D = D[neis]
        D/=D.sum()
          
#         neis = d.argsort()[:100]
        d = d[neis]
        
      
#         D = D[neis]

        diffs = np.array([D - d]).T
        Y[neis] -= 1*np.exp(-2*j/500)*diffs*(Y[i] - Y[neis])
    diffs       
    errors.append(np.linalg.norm(diffs))
#     if np.linalg.norm(diffs) < 0.004:
#         break
#     if br:
#         break
np.linalg.norm(diffs)

iteration 9

0.57951709971120502

In [ ]:
# plt.scatter(X.T[0], X.T[1], c = c, alpha = 0.7)
# plt.show()
# # Y = Y/(Y.max()-np.min(Y))
plt.scatter(Y.T[0], Y.T[1], c = C, edgecolors = 'none', alpha = 0.5)
plt.show()

plt.plot(range(len(errors)), errors, c='red')
plt.show()

In [ ]:
X.shape

In [201]:
(np.array([np.abs(d-D)]).T *(U))

array([[-0.01217785,  0.02469549],
       [-0.01814749, -0.01388979],
       [ 0.01987078,  0.00988317],
       [ 0.        ,  0.        ]])

In [12]:
d-D

array([-0.29245558, -0.05622856, -0.26120147,  0.        ])

In [195]:
(Y[0]-Y)/np.array([np.linalg.norm(Y - Y[0], axis = 1)]).T

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in divide
  if __name__ == '__main__':


array([[        nan,         nan],
       [ 0.96412704, -0.26544124],
       [-0.108855  , -0.99405764],
       [ 0.25747381, -0.96628528]])

In [225]:
U * props

array([[ 0.06533759, -0.07178333],
       [-0.14614889, -0.07681887],
       [ 0.21978114,  0.02284593],
       [ 0.        ,  0.        ]])

In [226]:
U

array([[ 0.67312406, -0.73952958],
       [-0.88517171, -0.46526449],
       [ 0.99464074,  0.10339146],
       [ 0.        ,  0.        ]])

In [227]:
props

array([[ 0.0970662 ],
       [ 0.16510795],
       [ 0.22096535],
       [ 0.        ]])

In [228]:
D

array([ 0.32828417,  0.32828417,  0.34343165,  0.        ])

In [229]:
d

array([ 3.38206474,  1.98830016,  1.55423306,  0.        ])

In [230]:
d/D

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in divide
  if __name__ == '__main__':


array([ 10.30224731,   6.05664338,   4.52559641,          nan])